---
phases:
  pre-build:
    commands:
      - "curl https://sh.rustup.rs -sSf | sh"
  build:
    commands:
      - "echo Build started on `date`"
      - "cargo run main.rs --release"
  post_build:
    commands:
      - "echo Build completed on `date`"
version: 0.1