---
phases:
  pre_build:
    commands:
      - "curl https://sh.rustup.rs -sSf | sh -s -- -y"
  build:
    commands:
      - "echo Build started on `date`"
      - "source $HOME/.cargo/env"
      - "cargo run main.rs --release"
  post_build:
    commands:
      - "echo Build completed on `date`"
version: 0.1