[package]
name = "discord_bot"
version = "0.1.0"
authors = ["<ericpinter99@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7.0"
regex = "1.1.9"

#serenity = {version="0.6.2",default-features=false,features=["client","rustls_backend"]}
serenity = "0.7.0"
reqwest = "0.9.18"
pest = "2.1.1"
pest_derive = "2.1.0"
lazy_static = "1.3.0"
serde = {version="1.0.94", features=["derive"]}
serde_json = "1.0.39"